FROM node:18-slim as base
WORKDIR /app
ARG VITE_API_HOST
ENV VITE_API_HOST $VITE_API_HOST
COPY . .
RUN npm install
RUN npm run build

FROM nginx:stable-alpine AS production
COPY --from=base /app/dist /usr/share/nginx/html/
RUN rm /etc/nginx/conf.d/default.conf  # <= This line solved my issue
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;" ]