{
 "title": "Cerbos",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Percentile", "query": "0.99, 0.95, 0.50" }
  ]
 },
 "panels": [
  {
   "title": "Num Policies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cerbos_dev_index_entry_count" }
   ]
  },
  {
   "title": "Engine",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(increase(cerbos_dev_engine_check_latency_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "sum(increase(grpc_io_server_server_latency_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "sum(increase(opencensus_io_http_server_latency_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency ($Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "repeat": "Percentile",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(${Percentile:raw}, sum(rate(grpc_io_server_server_latency_bucket[$__rate_interval])) by (le))",
     "legendFormat": "gRPC Server"
    },
    {
     "expr": "histogram_quantile(${Percentile:raw}, sum(rate(opencensus_io_http_server_latency_bucket[$__rate_interval])) by (le))",
     "legendFormat": "HTTP"
    },
    {
     "expr": "histogram_quantile(${Percentile:raw}, sum(rate(cerbos_dev_engine_check_latency_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Engine"
    },
    {
     "expr": "histogram_quantile(${Percentile:raw}, sum(rate(grpc_io_client_roundtrip_latency_bucket[$__rate_interval])) by (le))",
     "legendFormat": "gRPC client"
    },
    {
     "expr": "histogram_quantile(${Percentile:raw}, sum(rate(cerbos_dev_compiler_compile_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Compile"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs[$__rate_interval])) by (grpc_server_method, grpc_server_status)",
     "legendFormat": "{{grpc_server_method}}-{{grpc_server_status}}"
    },
    {
     "expr": "sum(rate(opencensus_io_http_server_request_count_by_method[$__rate_interval])) by (http_method)",
     "legendFormat": "HTTP-{{http_method}}"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"cerbos:3592\"}",
     "legendFormat": "open file descriptors"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"cerbos:3592\"}",
     "legendFormat": "Go Routines"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"cerbos:3592\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"cerbos:3592\"}",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "Go Memstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"cerbos:3592\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"cerbos:3592\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"cerbos:3592\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"cerbos:3592\"}",
     "legendFormat": "gc duration {{quantile}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    { "expr": "cerbos_dev_cache_max_size", "legendFormat": "{{kind}}.max" },
    { "expr": "cerbos_dev_cache_live_objects", "legendFormat": "{{kind}}.live" },
    {
     "expr": "sum(rate(cerbos_dev_cache_access_count[$__rate_interval])) by (kind, result)",
     "legendFormat": "{{kind}}-{{result}}"
    }
   ]
  }
 ]
}