server:
  httpListenAddr: ":3592"
  grpcListenAddr: ":3593"
storage:
  driver: "disk"
  disk:
    directory: /policies
    watchForChanges: true
tracing:
  serviceName: cerbos
  sampleProbability: 1
  exporter: otlp
  otlp:
    collectorEndpoint: "jaeger:4318"
