server:
  httpListenAddr: ":3592"
  grpcListenAddr: ":3593"
storage:
 driver: bundle
 bundle:
   remote:
     bundleLabel: production # The label to load policies for
     connection:
      apiEndpoint: https://api.stg-spitfire.cerbos.tech
      bootstrapEndpoint: https://cdn.stg-spitfire.cerbos.tech
   credentials:
     clientID: "LDLARHIJ0263" # ClientID
     clientSecret: "cerbos_bR6j/jsfjUp5YOVToLXZpEqrrhPoofH7LQWUcOZTBgc" # ClientSecret
     workspaceSecret: "CERBOS-1R1QC149ECJO6-M9N8DQN80WP9AU5Y2ZXHSP7RE534ADD73W3G7F648WFAE0PFSV8S2YY8TD" # WorkspaceSecret to decrypt the bundles -- generated during workspace creation
tracing:
  serviceName: cerbos
  sampleProbability: 1
  exporter: otlp
  otlp:
    collectorEndpoint: "jaeger:4318"
audit:
  enabled: true
  accessLogsEnabled: true
  decisionLogsEnabled: true
  backend: file
  file:
    path: stdout
