global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cerbos"
    scrape_interval: 5s
    metrics_path: /_cerbos/metrics
    static_configs:
      - targets: ["cerbos:3592"]

  - job_name: "expenses-api"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["server:9980"]
