{
 "title": "Expenses Application",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Expenses Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate by Path",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{app_kubernetes_io_name=\"expenses\", path=~\"/api/expenses.*\"}[1m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{app_kubernetes_io_name=\"expenses\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app_kubernetes_io_name=\"expenses\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app_kubernetes_io_name=\"expenses\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Cerbos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Cerbos Request Rate (1m by RPC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=\"cerbos\"}[1m])",
     "legendFormat": "{{grpc_server_method}}"
    }
   ]
  },
  {
   "title": "Cerbos Policy Index Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 11 },
   "targets": [
    { "expr": "cerbos_dev_index_entry_count", "legendFormat": "Policies" }
   ]
  },
  {
   "title": "Cerbos Decisions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "count(rate({app=\"cerbos\"} |= `EFFECT_ALLOW` | json | __error__=`` | line_format `{{.log}}` | json | log_kind = `decision` [1m]))",
     "legendFormat": "EFFECT_ALLOW"
    },
    {
     "expr": "count(rate({app=\"cerbos\"} |= `EFFECT_DENY` | json | __error__=`` | line_format `{{.log}}` | json | log_kind = `decision` [1m]))",
     "legendFormat": "EFFECY_DENY"
    },
    {
     "expr": "count(rate({app=\"cerbos\"} |= `PlanResource` | json | __error__=`` | line_format `{{.log}}` | json [1m]))",
     "legendFormat": "PLAN_RESOURCES"
    }
   ]
  },
  {
   "title": "Decision Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{app=\"cerbos\"} |= `EFFECT_` | json | __error__=`` | line_format `{{.log}}` | json | log_kind = `decision`"
    },
    {
     "expr": "{app=\"cerbos\"} |= `Plan` |= `cerbos.audit` | json | __error__=`` | line_format `{{.log}}` | json"
    }
   ]
  }
 ]
}